// 根 layout 用于处理全局样式和元数据，并提供全局 context 等事务
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/provider/theme-provider";
import SessionProvider from "@/components/provider/session-provider";
import { Toaster } from "@/components/ui/sonner";

import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession();
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session!}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
